// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addComment = `-- name: AddComment :exec
INSERT INTO comments (id, ticket_id, author_id, body, visibility)
VALUES ($1, $2, $3, $4, $5)
`

type AddCommentParams struct {
	ID         uuid.UUID `json:"id"`
	TicketID   uuid.UUID `json:"ticket_id"`
	AuthorID   uuid.UUID `json:"author_id"`
	Body       string    `json:"body"`
	Visibility string    `json:"visibility"`
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) error {
	_, err := q.db.ExecContext(ctx, addComment,
		arg.ID,
		arg.TicketID,
		arg.AuthorID,
		arg.Body,
		arg.Visibility,
	)
	return err
}

const createTicket = `-- name: CreateTicket :exec
INSERT INTO tickets (id, title, description, customer_id, status, priority, category, sla_due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTicketParams struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	CustomerID  uuid.UUID    `json:"customer_id"`
	Status      string       `json:"status"`
	Priority    string       `json:"priority"`
	Category    string       `json:"category"`
	SlaDueAt    sql.NullTime `json:"sla_due_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) error {
	_, err := q.db.ExecContext(ctx, createTicket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CustomerID,
		arg.Status,
		arg.Priority,
		arg.Category,
		arg.SlaDueAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash, role, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	return err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, title, description, customer_id, assignee_id, team_id, status, priority, category,
  sla_due_at, sla_paused_at, sla_remaining_seconds, breached_at, created_at, updated_at
FROM tickets WHERE id = $1
`

type GetTicketByIDRow struct {
	ID                  uuid.UUID     `json:"id"`
	Title               string        `json:"title"`
	Description         string        `json:"description"`
	CustomerID          uuid.UUID     `json:"customer_id"`
	AssigneeID          uuid.NullUUID `json:"assignee_id"`
	TeamID              uuid.NullUUID `json:"team_id"`
	Status              string        `json:"status"`
	Priority            string        `json:"priority"`
	Category            string        `json:"category"`
	SlaDueAt            sql.NullTime  `json:"sla_due_at"`
	SlaPausedAt         sql.NullTime  `json:"sla_paused_at"`
	SlaRemainingSeconds sql.NullInt64 `json:"sla_remaining_seconds"`
	BreachedAt          sql.NullTime  `json:"breached_at"`
	CreatedAt           time.Time     `json:"created_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (GetTicketByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketByID, id)
	var i GetTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CustomerID,
		&i.AssigneeID,
		&i.TeamID,
		&i.Status,
		&i.Priority,
		&i.Category,
		&i.SlaDueAt,
		&i.SlaPausedAt,
		&i.SlaRemainingSeconds,
		&i.BreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, status, created_at
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, status, created_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPublicComments = `-- name: ListPublicComments :many
SELECT id, ticket_id, author_id, body, visibility, created_at
FROM comments WHERE ticket_id = $1 AND deleted_at IS NULL AND visibility = 'public'
ORDER BY created_at
`

type ListPublicCommentsRow struct {
	ID         uuid.UUID `json:"id"`
	TicketID   uuid.UUID `json:"ticket_id"`
	AuthorID   uuid.UUID `json:"author_id"`
	Body       string    `json:"body"`
	Visibility string    `json:"visibility"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListPublicComments(ctx context.Context, ticketID uuid.UUID) ([]ListPublicCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicCommentsRow{}
	for rows.Next() {
		var i ListPublicCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorID,
			&i.Body,
			&i.Visibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
