// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlcgen

import (
	"context"
)

const getSlaPolicy = `-- name: GetSlaPolicy :one
SELECT priority, duration_seconds, updated_at FROM sla_policies WHERE priority = $1
`

func (q *Queries) GetSlaPolicy(ctx context.Context, priority string) (SlaPolicy, error) {
	row := q.db.QueryRowContext(ctx, getSlaPolicy, priority)
	var i SlaPolicy
	err := row.Scan(&i.Priority, &i.DurationSeconds, &i.UpdatedAt)
	return i, err
}

const health = `-- name: Health :one
SELECT 1
`

func (q *Queries) Health(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, health)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
