// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	ID         uuid.UUID `json:"id"`
	TicketID   uuid.UUID `json:"ticket_id"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
	Filename   string    `json:"filename"`
	StorageKey string    `json:"storage_key"`
	MimeType   string    `json:"mime_type"`
	SizeBytes  int64     `json:"size_bytes"`
	CreatedAt  time.Time `json:"created_at"`
}

type AuditEvent struct {
	ID        uuid.UUID       `json:"id"`
	TicketID  uuid.UUID       `json:"ticket_id"`
	ActorID   uuid.NullUUID   `json:"actor_id"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type CannedReply struct {
	ID        uuid.UUID     `json:"id"`
	Title     string        `json:"title"`
	Body      string        `json:"body"`
	TeamID    uuid.NullUUID `json:"team_id"`
	CreatedBy uuid.UUID     `json:"created_by"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Comment struct {
	ID         uuid.UUID    `json:"id"`
	TicketID   uuid.UUID    `json:"ticket_id"`
	AuthorID   uuid.UUID    `json:"author_id"`
	Body       string       `json:"body"`
	Visibility string       `json:"visibility"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type RefreshToken struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	TokenHash  string        `json:"token_hash"`
	ExpiresAt  time.Time     `json:"expires_at"`
	RevokedAt  sql.NullTime  `json:"revoked_at"`
	ReplacedBy uuid.NullUUID `json:"replaced_by"`
	CreatedAt  time.Time     `json:"created_at"`
}

type SavedFilter struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Name      string          `json:"name"`
	Query     json.RawMessage `json:"query"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type SlaPolicy struct {
	Priority        string    `json:"priority"`
	DurationSeconds int64     `json:"duration_seconds"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamMember struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

type Ticket struct {
	ID                  uuid.UUID     `json:"id"`
	Title               string        `json:"title"`
	Description         string        `json:"description"`
	CustomerID          uuid.UUID     `json:"customer_id"`
	AssigneeID          uuid.NullUUID `json:"assignee_id"`
	TeamID              uuid.NullUUID `json:"team_id"`
	Status              string        `json:"status"`
	Priority            string        `json:"priority"`
	Category            string        `json:"category"`
	SlaDueAt            sql.NullTime  `json:"sla_due_at"`
	SlaPausedAt         sql.NullTime  `json:"sla_paused_at"`
	SlaRemainingSeconds sql.NullInt64 `json:"sla_remaining_seconds"`
	BreachedAt          sql.NullTime  `json:"breached_at"`
	SearchVector        interface{}   `json:"search_vector"`
	CreatedAt           time.Time     `json:"created_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

type TicketStatusHistory struct {
	ID         uuid.UUID      `json:"id"`
	TicketID   uuid.UUID      `json:"ticket_id"`
	ActorID    uuid.UUID      `json:"actor_id"`
	FromStatus sql.NullString `json:"from_status"`
	ToStatus   string         `json:"to_status"`
	Reason     sql.NullString `json:"reason"`
	CreatedAt  time.Time      `json:"created_at"`
}

type TicketTag struct {
	TicketID uuid.UUID `json:"ticket_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
